# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Federico Ramallo
tagline:             "Entrepreneur, Full stack developer, and Problem solver"
description:         'Federico Ramallo can build software and help teams to do it better.'
url:                 http://framallo.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Federico Ramallo
  url:               https://twitter.com/framallo
  email:             framallo@gmail.com


# Custom vars
version:             1.0.0

exclude: ['previous_posts', 'server_setup']

