# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Federico Ramallo
tagline:             "Entrepreneur, Full stack developer, and Coach"
description:         'Federico Ramallo loves solving problems, coding, motorcycles and adventures.'
url:                 http://framallo.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Federico Ramallo
  url:               https://twitter.com/framallo
  email:             framallo@gmail.com


# Custom vars
version:             1.0.0
